"""Versioned BDSubMerge project persistence."""

from .atomic_writer import (
    AtomicProjectWriteError,
    atomic_project_writer,
    atomic_save_project,
)
from .conversion import (
    OutputState,
    ProjectState,
    RestoredProject,
    SubtitleState,
    build_project_snapshot,
    restore_project_state,
)
from .migration import migrate_payload
from .paths import (
    check_project_sources,
    find_relocation_candidates,
    fingerprint,
    relocate_source,
    resolve_output_path,
    resolve_path,
    snapshot_file,
    store_path,
)
from .persistence import (
    dump_project_bytes,
    dumps_project,
    load_project_bytes,
    loads_project,
    project_from_data,
    project_to_data,
    save_project,
)
from .schema import (
    CURRENT_SCHEMA_VERSION,
    BoundarySnapshot,
    ConflictPolicySnapshot,
    FileFingerprint,
    FileSnapshot,
    MappingSnapshot,
    OutputSnapshot,
    PlaylistSnapshot,
    ProjectSchemaError,
    ProjectSnapshot,
    SourceCheck,
    SourceState,
    StoredPath,
    SubtitleSnapshot,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "AtomicProjectWriteError",
    "BoundarySnapshot",
    "ConflictPolicySnapshot",
    "FileFingerprint",
    "FileSnapshot",
    "MappingSnapshot",
    "OutputSnapshot",
    "OutputState",
    "PlaylistSnapshot",
    "ProjectSchemaError",
    "ProjectSnapshot",
    "ProjectState",
    "RestoredProject",
    "SourceCheck",
    "SourceState",
    "StoredPath",
    "SubtitleSnapshot",
    "SubtitleState",
    "atomic_project_writer",
    "atomic_save_project",
    "build_project_snapshot",
    "check_project_sources",
    "dump_project_bytes",
    "dumps_project",
    "find_relocation_candidates",
    "fingerprint",
    "load_project_bytes",
    "loads_project",
    "migrate_payload",
    "project_from_data",
    "project_to_data",
    "relocate_source",
    "resolve_output_path",
    "resolve_path",
    "restore_project_state",
    "save_project",
    "snapshot_file",
    "store_path",
]
