"""Shared application services for CLI and GUI surfaces."""

from .models import (
    ApplicationIssue,
    ApplicationSeverity,
    ExecuteMergeRequest,
    ExecuteMergeResult,
    ImportSubtitlesRequest,
    ImportSubtitlesResult,
    InspectRequest,
    InspectResult,
    LoadSubtitlesRequest,
    LoadSubtitlesResult,
    PreparedMerge,
    PreparedSource,
    PrepareMergeRequest,
    ScanRequest,
    ScanResult,
    SubtitleAsset,
    SubtitleInput,
)
from .playlist_selection import (
    JRIVER_INCOMPATIBLE_WARNING,
    PlaylistEquivalenceGroup,
    PlaylistSelectionRequest,
    PlaylistSelectionResult,
    select_playlists,
)
from .reporting import (
    MergeExecutionReport,
    MergeReportFormat,
    MergeReportTarget,
    ReportEpisode,
    ReportNotice,
    ReportPlayItem,
    ReportPlaylist,
    ReportSourceFingerprint,
    ReportStyleRename,
)
from .services import (
    BdmvApplicationService,
    MergeApplicationService,
    SubtitleApplicationService,
    build_playlist_boundaries,
)
from .subtitle_discovery import (
    SUPPORTED_SUBTITLE_SUFFIXES,
    append_discovered_subtitle_paths,
    discover_subtitle_paths,
    natural_path_key,
)

__all__ = [
    "JRIVER_INCOMPATIBLE_WARNING",
    "SUPPORTED_SUBTITLE_SUFFIXES",
    "ApplicationIssue",
    "ApplicationSeverity",
    "BdmvApplicationService",
    "ExecuteMergeRequest",
    "ExecuteMergeResult",
    "ImportSubtitlesRequest",
    "ImportSubtitlesResult",
    "InspectRequest",
    "InspectResult",
    "LoadSubtitlesRequest",
    "LoadSubtitlesResult",
    "MergeApplicationService",
    "MergeExecutionReport",
    "MergeReportFormat",
    "MergeReportTarget",
    "PlaylistEquivalenceGroup",
    "PlaylistSelectionRequest",
    "PlaylistSelectionResult",
    "PrepareMergeRequest",
    "PreparedMerge",
    "PreparedSource",
    "ReportEpisode",
    "ReportNotice",
    "ReportPlayItem",
    "ReportPlaylist",
    "ReportSourceFingerprint",
    "ReportStyleRename",
    "ScanRequest",
    "ScanResult",
    "SubtitleApplicationService",
    "SubtitleAsset",
    "SubtitleInput",
    "append_discovered_subtitle_paths",
    "build_playlist_boundaries",
    "discover_subtitle_paths",
    "natural_path_key",
    "select_playlists",
]
